language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '7'
  - '6'
script:
  - yarn run test
after_success:
  - yarn run semantic-release
after_script: 'cat ./coverage/lcov.info | coveralls'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
